### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.gradcheck'

### ISSUE THREAD

**Issue by voaneves** [alan-barzilay/NLPortugues#13]
Hello,

I encountered an error today while trying to execute python run.py, in the EP1 folder:

```
Traceback (most recent call last):
  File "C:\Users\victo\OneDrive\Desktop\NLPortugues-master\NLPortugues-master\EP 1\run.py", line 11, in <module>
    from word2vec import *
  File "C:\Users\victo\OneDrive\Desktop\NLPortugues-master\NLPortugues-master\EP 1\word2vec.py", line 6, in <module>
    from utils.gradcheck import gradcheck_naive, grad_tests_softmax, grad_tests_negsamp
ModuleNotFoundError: No module named 'utils.gradcheck'
```

Is it safe to remove the import line for utils? The necessary functionalities from utils are already implemented throughout the file. 

Thanks!

**Comment by voaneves** [comment]
@alan-barzilay could you have a look?
